version: "3.7"
services:
    gateway:
        image: ${REGISTRY}/${PROJECT_NAME}-gateway:${IMAGE_TAG}
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
            - api

    frontend:
        image: ${REGISTRY}/${PROJECT_NAME}-frontend:${IMAGE_TAG}
        restart: always

    api:
        image: ${REGISTRY}/${PROJECT_NAME}-api:${IMAGE_TAG}
        restart: always
        depends_on:
            - api-php-fpm

    api-php-fpm:
        image: ${REGISTRY}/${PROJECT_NAME}-api-php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USER: ${API_MAILER_USER}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_ENCRYPTION: tls
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://${DOMAIN}
            API_URL: https://api.${DOMAIN}
            SENTRY_DSN: ${SENTRY_DSN}
            ENCRYPTION_KEY: ${ENCRYPTION_KEY}

    api-php-cli:
        image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USER: ${API_MAILER_USER}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_ENCRYPTION: tls
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://${DOMAIN}
            API_URL: https://api.${DOMAIN}
            SENTRY_DSN: ${SENTRY_DSN}
            ENCRYPTION_KEY: ${ENCRYPTION_KEY}

    api-postgres:
        image: postgres:12.2-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${API_DB_PASSWORD}
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data

volumes:
    api-postgres:
